# automation configuration for updating ARSO weather sensor # put this in automation.yaml file

- id: '1713264720281'
  alias: ARSO weather forecast update sensor
  description: update ARSO weather forecast
  trigger:
  - platform: time_pattern
    hours: 1
  action:
  - service: homeassistant.update_entity
    target:
      entity_id: sensor.arso_forecast
  mode: single